CC = gcc
CFLAGS = -Wall -g
OBJS = server.o user.o

all: server user

server: server.o
    $(CC) $(CFLAGS) -o server server.o

user: user.o
    $(CC) $(CFLAGS) -o user user.o

server.o: server.c communication.h
    $(CC) $(CFLAGS) -c server.c

user.o: user.c communication.h
    $(CC) $(CFLAGS) -c user.c

clean:
    rm -f $(OBJS) server user